apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xtineskim/argocon-cilium.git
    path: charts/cilium
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system 
  syncPolicy:
    automated:
      selfHeal: true
